export const ADD_CONSERGE = 'ADD_CONSERGE';
export const ADD_CONSERGE_SUCCESS = 'ADD_CONSERGE_SUCCESS';
export const ADD_CONSERGE_ERROR = 'ADD_CONSERGE_ERROR';

export const EDIT_CONSERGE = 'EDIT_CONSERGE';
export const EDIT_CONSERGE_SUCCESS = 'EDIT_CONSERGE_SUCCESS';
export const EDIT_CONSERGE_ERROR = 'EDIT_CONSERGE_ERROR';

export const DELETE_CONSERGE = 'DELETE_CONSERGE';
export const DELETE_CONSERGE_SUCCESS = 'DELETE_CONSERGE_SUCCESS';
export const DELETE_CONSERGE_ERROR = 'DELETE_CONSERGE_ERROR';

export const GET_CONSERGE = 'GET_CONSERGE';
export const GET_CONSERGE_SUCCESS = 'GET_CONSERGE_SUCCESS';
export const GET_CONSERGE_ERROR = 'GET_CONSERGE_ERROR';

export const GET_CONSERGES = 'GET_CONSERGES';
export const GET_CONSERGES_SUCCESS = 'GET_CONSERGES_SUCCESS';
export const GET_CONSERGES_ERROR = 'GET_CONSERGES_ERROR';

export const SET_CONSERGE = 'SET_CONSERGE';